apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-config
  namespace: default
data:
  quote: {{ quote .Values.city }}
  upper: {{ upper .Values.city }}
  now: {{ now }}
  substr: {{ substr 0 3 .Values.city }}
  network: {{getHostByName "curso" }}
  network: {{getHostByName "www.google.com" }}